REGIONAL_SEARCH_CONFIG = {
    "North America": [
        "United States healthcare AI news",
        "FDA artificial intelligence medical device news",
        "Canada healthcare AI news",
        "Mayo Clinic artificial intelligence healthcare",
        "Epic healthcare AI news",
        "Google Health AI medical news",
        "Microsoft healthcare AI news",
        "NVIDIA healthcare AI news",
    ],
    "Latin America": [
        "Latin America healthcare AI news",
        "Brazil artificial intelligence healthcare news",
        "Mexico digital health AI news",
        "Colombia healthcare AI news",
        "Argentina healthtech artificial intelligence",
        "Chile healthcare AI startup",
        "telemedicine AI Latin America healthcare",
    ],
    "Europe": [
        "Europe healthcare AI news",
        "NHS artificial intelligence healthcare news",
        "EU AI Act healthcare medical AI",
        "Germany healthcare AI news",
        "France healthcare AI news",
        "EMA artificial intelligence medical device",
        "CE marked AI medical device Europe",
    ],
    "Asia": [
        "Asia healthcare AI news",
        "India healthcare AI hospital news",
        "China healthcare artificial intelligence news",
        "Japan healthcare robotics AI news",
        "Singapore healthtech AI news",
        "South Korea medical AI news",
        "AI hospital Asia healthcare",
    ],
    "Africa": [
        "Africa healthcare AI news",
        "Nigeria healthtech artificial intelligence",
        "Kenya digital health AI news",
        "South Africa healthcare AI news",
        "Ghana healthtech AI",
        "Egypt healthcare artificial intelligence",
        "WHO Africa digital health AI",
    ],
}
